config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about', to: 'welcome#about'
  get 'terms_of_use', to: 'welcome#terms_of_use'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'search', to: 'welcome#search'
  get 'show', to: 'welcome#show'
  get 'check_email', to: 'welcome#check_email'
  get :dashboard, to: 'teachers#dashboard', as: :dashboard
  get 'faq_home_page', to: 'welcome#faq_home_page'
  get '/contact_us', to: 'welcome#contact_us', as: :contact
  post 'support', to: 'welcome#support'



  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :teachers do
    member do
      get :set_password
      patch :update_password
      post :set_availability
      get :availability
      get :child_enrollment
      match :bank_account, via: [:get, :post]
      get :get_price
      get :get_schedule
      post :tour_booking
      get :enroll_modal   
    end
    collection do
      get :document
      get :get_availability
      get :bank_account_detail
      get :manage_enrollment
    end
  end

  resources :children do
    member do
      get :abcd
    end
  end

  get '/parents/check_email_availability', to: 'parents#check_email_availability'
  get '/parents/dashboard', to: 'parents#dashboard'

  resources :parent_profiles

  resources :teacher_profiles do
    member do
      get :request_info
    end
  end

  resources :parents, only: [:create] do
    member do
      get :school
      get :interest_open_house
      match :payment, via: [:get, :post]
    end
    collection do
      get :change_favourite_status
      get :login
      get :child_birth
      get :set_child_admission
      put :toggle_favourite_status
    end
  end
  resources :enrollments do
    member do
      get :change_enrollment_status
    end
  end

  namespace :admin do
    get '', to: "teachers#index", as: :dashboard
    resources :teachers, only: [:index, :edit, :update] do
      member do
        match :price, via: [:get, :post]
        get :teacher_price
        get :edit_profile
        patch :approve
        patch :reject
        get :set_transaction
      end
      collection do
        match :upload_document, via: [:get, :post, :delete]
        get :document
        get :transaction_setting
      end
    end
    resources :parents
  end
  get '/partner', to: "teachers#new", as: :partner
end

app/models/teacher.rb
class Teacher < User
  has_one :teacher_profile, foreign_key: :teacher_id, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  has_many :prices,  dependent: :destroy
  has_many :tour_requests, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :children
  has_many :payments
  has_many :enrollments
  delegate :first_name, :last_name, :street_address, :date_of_birth, to: :teacher_profile, allow_nil: true

  after_create :notify_admin_for_new_application
  # after_create :notify_support_and_user
  def notify_admin_for_new_application
    ['self.email', 'support@dreamschools.co', 'admin@dreamschool.com'].each do |email|
      UserMailer.notify_admin_for_new_application(self, email).deliver_now
    end
    #UserMailer.notify_admin_for_new_application(self).deliver_now
  end

  # def notify_support_and_user
  #   ['self.email', 'support@dreamschools.co'].each |email|
  #     UserMailer.notify_support_and_user(email).deliver_now
  #   end
  # end

end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::AdminBaseController
  before_action :set_teacher, except: [:index, :upload_document, :document, :transaction_setting]

  def index
    @teachers = Teacher.all.order(:id)
  end

  def edit_profile
    @teacher_profile = @teacher.teacher_profile.present? ? @teacher.teacher_profile : @teacher.build_teacher_profile
  end

  def update
    @teacher_profile = @teacher.teacher_profile.present? ? @teacher.teacher_profile : @teacher.build_teacher_profile
    if @teacher_profile.present? && @teacher_profile.update_attributes(permitted_teacher_params)
      flash[:notice] = 'Teacher profile successfully updated.'
      redirect_to admin_teachers_path
    else
      flash[:notice] = 'Something went wrong! Try again later.'
      render :new
    end
  end

  def approve
    if @teacher.present? && @teacher.update_attribute(:approve, true)
      UserMailer.teacher_invitaion_email(@teacher).deliver_now
      flash[:notice] = 'Teacher successfully approved.'
    else
      flash[:notice] = 'Something went wrong! Try again later.'
    end
    redirect_to admin_teachers_path
  end

  def reject
    if @teacher.present? && @teacher.update_attribute(:approve, false)
      flash[:notice] = 'Teacher successfully rejected.'
    else
      flash[:notice] = 'Something went wrong! Try again later.'
    end
    redirect_to admin_teachers_path
  end

  def price
    if request.get?
      @price = Price.new
      @teacher_prices = @teacher.prices if @teacher.prices.present?
    elsif request.post?
      @teacher.prices.destroy_all
      params[:price].each do |k, v|
        @price = @teacher.prices.new(child_time: v[:child_time].to_i, two_days_price: v[:two_days_price], three_days_price: v[:three_days_price], five_days_price: v[:five_days_price])
        if @price.save
          flash[:notice] = 'Teacher availability successfully created.'
        else
          flash[:notice] = 'Something went wrong! Try again later.'
        end
      end
      redirect_to teacher_price_admin_teacher_path(@teacher)
    end
  end

  def teacher_price
    @prices = @teacher.prices
  end

  def upload_document
    if request.get?
      @document = AdminInfo.new
    elsif request.post?
      @document = AdminInfo.new(document_params)
      if @document.save
        redirect_to document_admin_teachers_path, notice: "The document #{@document.name} has been uploaded."
      else
        render "upload_documnet"
       end
    elsif request.delete?
      @document = AdminInfo.find(params[:document_id])
      if @document.destroy
        redirect_to document_admin_teachers_path, notice: "The document #{@document.name} has been deleted."
      else
        redirect_to document_admin_teachers_path, notice: "Something went wrong! Try again later."
       end
    end
  end

  def document 
    @documents = AdminInfo.all
  end

  def transaction_setting
    @teacher = Teacher.all
  end

  def set_transaction
    teacher_profile = TeacherProfile.find(params[:id])
    teacher_profile.update_attributes(transaction_fee: params[:teacher_profile][:transaction_fee])
    redirect_to transaction_setting_admin_teachers_path, notice: 'transaction_fee successfully created'
  end

  private
    def permitted_teacher_params
      params.require(:teacher_profile).permit(
        :first_name, :last_name, :street_address,
        :apt_no, :city, :home_phone, :cell_phone,
        :date_of_birth, :language, :work,
        :legal_to_work, :apartment, :floor,
        :condo, :house, :basement_premises, :two_exit,
        :home_smoke, :pet, :vaccine, :goal, :age_range,
        :local_school, :school_name, :request_info, :tour, :open_house,
        :comments, :profile_image, :cover_photo,
        children_attributes: [:id, :full_name, :age, :care_by, :_destroy]
      )
    end

    def permmited_price_param
      params.require(:price).permit(
        :child_time, :two_days_price, :three_days_price, :five_days_price
      )
    end

    def document_params
      params.require(:admin_info).permit(
        :name, :document
        )
    end

    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  layout :set_layout
  before_action :authenticate_user!, except: [:show, :new, :create, :set_password, :update_password]
  before_action :authenticate_user!, except: [:show, :new, :create, :set_password, :update_password]
  before_action :set_teacher, only: [ :update_password, :set_password ]
  before_action :ensure_teacher, only: [:dashboard, :child_enrollment]

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(permitted_teacher_params)
    if @teacher.save
      @teacher.invitation_token
      redirect_to root_path, notice: "Thanks for register, We are reviewing your application. You will receive an email upon approval of your profile."
    else
      redirect_to partner_path, alert: "Something went wrong! Please try again."
    end
  end

  def show
  end

  def update_password
    if @teacher.update(permitted_teacher_password_params)
      bypass_sign_in(@teacher)
      redirect_to new_teacher_profile_path, notice: 'Your password has been set successfully. You can now update your profile.'
    else
      redirect_to root_path, alert: 'Password could not be set.'
    end
  end

  def dashboard
    unless current_user.teacher_profile.presence
      redirect_to new_teacher_profile_path, notice: 'You need to update your profile!'
    end
  end

  def enroll_modal;  end

  def document
    @documents = AdminInfo.all
  end

  def get_price
    teacher = Teacher.find(params[:id])
    redirect_to teacher_profile_path(teacher.teacher_profile) unless request.xhr?
    @prices = Teacher.find(params[:id]).prices
  end

  def get_schedule
    @tour_request = TourRequest.new
    @teacher = Teacher.find(params[:id])
    day = params[:date].to_date.wday == 0 ? 7 : params[:date].to_date.wday
    availabilty = @teacher.availabilities.where(day_index: day)
    if availabilty.present?
      @start_time = availabilty.first.start_time.to_s(:time)
      @end_time = availabilty.first.end_time.to_s(:time)
    end
  end

  def tour_booking
    @teacher = Teacher.find(params[:id])
    tour_request = current_user.tour_requests.new(permitted_tour_request_param)
    @status = tour_request.save ? true : false
  end

  def availability
  end

  def set_availability
    calander_events = JSON.parse(params[:calander_events])
    if calander_events.present?
      current_user.availabilities.destroy_all
      calander_events.each do |ce|
        @availability = current_user.availabilities.new(day_index: ce["week_day"], start_time: ce["hour_from"], end_time: ce["hour_to"])
        if @availability.save
          flash[:notice] = 'Teacher availability successfully created.'
        else
          flash[:notice] = 'Something went wrong! Try again later.'
        end
      end
    end
    redirect_to availability_teacher_path
  end

  def get_availability
    get_availabilities = current_user.availabilities
    availabilities = get_availabilities.map do |availabilitly|
      {
        day_of_week: availabilitly.day_index,
        start_hour: availabilitly.start_time.strftime("%H:%M:%S"),
        end_hour: availabilitly.end_time.strftime("%H:%M:%S")
      }
    end
    render json: availabilities
  end

  def bank_account_detail
    stripe_account_id = current_user.teacher_profile.stripe_account_id
    begin
      @stripe_account_details = Stripe::Account.retrieve(stripe_account_id)
    rescue Exception => e
      redirect_to dashboard_path, alert: e.message
    end
  end

  def bank_account
    unless request.get?
      file = File.new(params[:stripe_verification_file].path) rescue nil
      upload_result = upload_identity(file)
      begin
        stripe_account = Stripe::Account.create({
          type: 'custom',
          country: 'US',
          email: current_user.email,
          legal_entity: {
            type: 'individual',
            first_name: current_user.first_name,
            last_name:  current_user.last_name,
            address: {
              city: params[:address_city],
              state: params[:address_state],
              country: 'US',
              postal_code: params[:address_postal_code],
              line1: params[:address_line1],
            },
            dob: {
              day: params[:birth_date].to_date.day,
              month: params[:birth_date].to_date.month,
              year: params[:birth_date].to_date.year,
            },
            verification: {
              document: upload_result.id,
            },
          },
          external_account: {
            object: 'bank_account',
            country: 'US',
            currency: 'usd',
            account_number: params[:bank_account_number],
            account_holder_name: params[:bank_holder_name],
            routing_number: params[:bank_routing_number],
            account_holder_type: 'individual',
          },

          tos_acceptance: {
            date: Time.now.to_i,
            ip: request.remote_ip,
          }
        })

        current_user.teacher_profile.update_attributes(stripe_account_id: stripe_account.id) if stripe_account.present?
        redirect_to bank_account_detail_teachers_path, notice: 'Your Bank account information is successfully updated'
      rescue Stripe::StripeError => e
        flash[:error] = e.message
        render 'bank_account'
      end
    end
  end

  def manage_enrollment
    @enrollments = current_user.enrollments
  end

  def set_password
    @teacher
  end

  def child_enrollment
    enroll = Enrollment.find(params[:enroll])
    if params[:status]
      enroll.update_attributes(status: params[:status])
      UserMailer.make_payment_link(enroll).deliver_now
    else
      enroll.update_attributes(status: params[:status])
    end
    redirect_to dashboard_path
  end
end
  private

    def upload_identity(file)
      Stripe::FileUpload.create(
        {
          purpose: 'identity_document',
          file: file
        },
      )
    end

    def set_teacher
      @teacher ||= Teacher.find_by(invitation_token: params[:token])
    end

    def permitted_teacher_password_params
      params.require(:teacher).permit(
        :password,
        :password_confirmation
      )
    end

    def permitted_tour_request_param
      params.require(:tour_request).permit(
        :tour_date,
        :tour_time,
        :phone,
        :teacher_id
      )
    end

    def permitted_teacher_params
      params[:teacher][:password] = Devise.friendly_token.first(8)
      params.require(:teacher).permit(
        :name,
        :email,
        :telephone_no,
        :postal_code,
        :password
      )
    end

    def set_layout
      case action_name
      when 'dashboard', 'availability', 'bank_account', 'bank_account_detail', 'document', 'manage_enrollment'
        'admin'
      else
        'application'
      end
    end

    def ensure_teacher
      unless current_user && current_user.teacher?
        redirect_to admin_dashboard_path
      end
    end

app/helpers/admin/teachers_helper.rb
module Admin::TeachersHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/teachers/_child_fields.html.erb
<div class='nested-fields'>
  <%=f.input :full_name, label: 'Full _name', placeholder: 'Full Name' %>
  <%= f.input :age, label: 'Age', placeholder: 'Age' %>
  <%= f.input :care_by, as: :select, label: '*Care provided by', collection: Child::CARE_BY, include_blank: false, include_hidden: false %>
  <%= link_to_remove_association "remove child", f %>
</div>

app/views/admin/teachers/_price_edit.html.erb
<%= form_for(@price, url: price_admin_teacher_path, html: { method: :post }) do |f| %>
  <table class="table">
    <tbody>
      <tr>
        <th></th>
        <th>2 days/wk</th>
        <th>3 days/wk</th>
        <th>5 days/wk</th>
      </tr>
      <% @teacher_prices.each_with_index do |tp, index| %>
        <tr>
          <%= f.fields_for "#{index}" do |option| %>
            <td><%= label_tag 'day_time_over_2', tp.child_time%></td>
            <%= option.hidden_field :child_time, value: Price.child_times[tp.child_time]%>
            <td><%= option.number_field :two_days_price, value: tp.two_days_price, class: "form-control", required: true %></td>
            <td><%= option.number_field :three_days_price, value: tp.three_days_price, class: "form-control", required: true %></td>
            <td><%= option.number_field :five_days_price, value: tp.five_days_price, class: "form-control", required: true %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="form-actions">
    <%=f.submit 'Submit', class: 'btn btn-primary btn-custom'%>
  </div>
<% end %>

app/views/admin/teachers/_price_new.html.erb
<h3>Create Teacher Price </h3>
<%= form_for(@price, url: price_admin_teacher_path, html: { method: :post }) do |f| %>
  <table class="table">
  <tbody>
    <tr>
      <th></th>
      <th>2 days/wk</th>
      <th>3 days/wk</th>
      <th>5 days/wk</th>
    </tr>
    <tr>
      <%= f.fields_for '0' do |first_option| %>
        <td class="day_time_over_2"><%= label_tag 'full_day_1_18', 'Full Day, 1-18 months'%></td>
        <%= first_option.hidden_field :child_time, value: Price.child_times['Full Day, 1-18 months'] %>
        <td class="Box-size"><%= first_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= first_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= first_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '1' do |second_option| %>
        <td class="day_time_over_2"><%= label_tag 'full_day_18_30', 'Full Day, 18-30 months'%></td>
        <%= second_option.hidden_field :child_time, value: Price.child_times['Full Day, 18-30 months'] %>
        <td class="Box-size"><%= second_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= second_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= second_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '2' do |third_option| %>
        <td class="day_time_over_2"><%= label_tag 'full_day_31_72', 'Full Day, 31-72 months'%></td>
        <%= third_option.hidden_field :child_time, value: Price.child_times['Full Day, 31-72 months'] %>
        <td class="Box-size"><%= third_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= third_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= third_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '3' do |fourth_option| %>
        <td class="day_time_over_2"><%= label_tag 'half_day_1_18', 'Half Day, 1-18 months'%></td>
        <%= fourth_option.hidden_field :child_time, value: Price.child_times['Half Day, 1-18 months'] %>
        <td class="Box-size"><%= fourth_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= fourth_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= fourth_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    <tr>
      <%= f.fields_for '4' do |fifth_option| %>
        <td class="day_time_over_2"><%= label_tag 'half_day_18_30', 'Half Day, 18-30 months'%></td>
        <%= fifth_option.hidden_field :child_time, value: Price.child_times['Half Day, 18-30 months'] %>
        <td class="Box-size"><%= fifth_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= fifth_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= fifth_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '5' do |sixth_option| %>
        <td class="day_time_over_2"><%= label_tag 'half_day_31_72', 'Half Day, 31-72 months'%></td>
        <%= sixth_option.hidden_field :child_time, value: Price.child_times['Half Day, 31-72 months'] %>
        <td class="Box-size"><%= sixth_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= sixth_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= sixth_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '6' do |seventh_option| %>
        <td class="day_time_over_2"><%= label_tag 'night_time_1_18', 'Nighttime, 1-18 months'%></td>
        <%= seventh_option.hidden_field :child_time, value: Price.child_times['Nighttime, 1-18 months'] %>
        <td class="Box-size"><%= seventh_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= seventh_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= seventh_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '7' do |eight_option| %>
        <td class="day_time_over_2"><%= label_tag 'night_time_18_30', 'Nighttime, 18-30 months'%></td>
        <%= eight_option.hidden_field :child_time, value: Price.child_times['Nighttime, 18-30 months'] %>
        <td class="Box-size"><%= eight_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= eight_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= eight_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    </tr>
    <tr>
      <%= f.fields_for '8' do |ninth_option| %>
        <td class="day_time_over_2"><%= label_tag 'night_time_under_2', 'Nighttime, 31-72 months'%></td>
        <%= ninth_option.hidden_field :child_time, value: Price.child_times['Nighttime, 31-72 months'] %>
        <td class="Box-size"><%= ninth_option.number_field :two_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= ninth_option.number_field :three_days_price, class: "form-control", required: true %></td>
        <td class="Box-size"><%= ninth_option.number_field :five_days_price, class: "form-control", required: true %></td>
      <% end%>
    <tr>

  </table>
  <div class="form-actions">
    <%=f.submit 'Submit', class: 'btn btn-primary btn-custom'%>
  </div>
<% end %>

app/views/admin/teachers/document.html.erb
<div class="form-content">
<br/>
<%= link_to "New Document", upload_document_admin_teachers_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |doc| %>
      <tr>
        <td><%= doc.name %></td>
        <td><%= link_to "Download Document", doc.document_url, download: doc.name %></td>
        <td><%= button_to "Delete",  upload_document_admin_teachers_path(document_id: doc.id), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{doc.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/teachers/edit.html.erb
<div class="form-content">
  <%= simple_form_for @teacher_profile, url: admin_teacher_path, method: 'put', html: { class: 'form-horizontal' } do |f| %>
    <h1> Personal Information </h1>
      <%= f.input :first_name%>
      <%= f.input :last_name %>
      <%= f.input :street_address %>
      <%= f.input :apt_no%>
      <div class='form-group'>
        <%= label_tag 'postal_code', 'Postal Code'%>
        <input class="form-control string required" type="text" value="<%= current_user.postal_code%>" disabled="true">
      </div>
      <%= f.input :city%>
      <%= f.input :home_phone%>
      <%= f.input :cell_phone%>
      <%= f.input :date_of_birth%>
      <%= f.input :language%>
      <%= f.input :work%>
      <%= f.input :legal_to_work, :as => :select, :label => 'Are you legally able to work in Canada? (Have SIN or applied for it)', :collection => option_with_na, include_blank: false, include_hidden: false %>

      <%= f.input :apartment, inline_label: 'Apartment:' %>
      <div id = "apartment">
        <%= f.input :floor%>
        <%= f.input :condo, as: :select, collection: choose_option, label: '*If Apartment, is this a Condo?'%>
      </div>
      <%= f.input :house, inline_label: 'House:' %>
      <div id = "house">
        <%= f.input :basement_premises, as: :select, collection: choose_option, label: 'Is child care space in the basement of the premises?'%>
        <%= f.input :basement_premises, as: :select, collection: choose_option, label: '*Are there two exits?'%>
      </div>
      <%= f.input :home_smoke, as: :select, label: '*Smoking in home:', collection: choose_option, include_blank: false, include_hidden: false %>

      <%= f.input :pet, as: :select, label: '*Pets in home?', collection: choose_option, include_blank: false, include_hidden: false %>

      <%= f.input :vaccine, as: :select, label: '*Vaccinations are current?', collection: option_with_na, include_blank: false, include_hidden: false %>

    <h4> CHILDREN IN HOME: </h4>
      <div id='children'>
        <%= f.simple_fields_for :children do |child| %>
          <%= render 'child_fields', :f => child %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'add child', f, :children %>
        </div>
      </div>
    <%= f.input :goal, label: 'GOAL:' %>
    <%= f.input :age_range, label: 'Age range you want to have?' %>
    <%= f.input :local_school, as: :select, collection: choose_option, label: '*Are you willing to take children to local schools?' %>
    <%= f.input :school_name, label: 'Name of School(s):' %>
    <%= f.input :comments, label: 'Comments' %>
    <div class="form-actions">
      <%=f.submit 'Submit', class: 'btn btn-primary btn-custom'%>
    </div>
  <% end %>

app/views/admin/teachers/index.html.erb
<h1>Teachers applications</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Postal Code</th>
      <th colspan="5">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>    
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.postal_code %></td>
        <% if teacher.approve %>
          <td><%= link_to 'Edit Profile', edit_profile_admin_teacher_path(teacher)%></td>
          <!-- <td><%#= link_to 'Edit Page', teacher_profile_path(teacher.teacher_profile) %></td> -->
          <% if teacher.teacher_profile.present? %>
            <td><%= link_to 'Show', teacher_profile_path(teacher.teacher_profile) %></td>
          <% end %>
          <td><%= link_to 'Reject', reject_admin_teacher_path(teacher), method: :patch %></td>
          <td><%= link_to 'Set Price', price_admin_teacher_path(teacher), method: :get %></td>
        <% else%>
          <td><%= link_to 'Approve', approve_admin_teacher_path(teacher), method: :patch %></td>
          <td></td>
          <td></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/teachers/price.html.erb
<div class="form-content">
  <% if @teacher_prices.nil? %>
    <%= render 'price_new' %>
  <% else %>
    <%= render 'price_edit' %>
  <% end %>
</div>

app/views/admin/teachers/transaction_setting.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Transaction Fee</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @teacher.each do |teacher| %>
      <% if teacher.teacher_profile.present? %>
        <tr>
          <td><%= teacher.name %></td>
          <td><%= teacher.email %></td>
          <%= simple_form_for teacher.teacher_profile, url: set_transaction_admin_teacher_path(teacher.teacher_profile), method: :get do |f| %>
            <td><%= f.input :transaction_fee, label: false, required: true, input_html: { class: 'field_size' } %></td>
            <td><%= f.submit "Set Fee", class: "btn btn-primary" %></td>
          <% end %>
        </tr>
      <% end %>
    <%end%>    
  </tbody>
</table>

app/views/admin/teachers/upload_document.html.erb
<% if !@document.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-content">
  <%= simple_form_for @document, url: upload_document_admin_teachers_path, method: :post, html: { class: 'form-horizontal' } do |f| %>
    <%= f.input :name, autofocus: true %>
    <%= f.input :document, as: :file%>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>