config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about', to: 'welcome#about'
  get 'terms_of_use', to: 'welcome#terms_of_use'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'search', to: 'welcome#search'
  get 'show', to: 'welcome#show'
  get 'check_email', to: 'welcome#check_email'
  get :dashboard, to: 'teachers#dashboard', as: :dashboard
  get 'faq_home_page', to: 'welcome#faq_home_page'
  get '/contact_us', to: 'welcome#contact_us', as: :contact
  post 'support', to: 'welcome#support'



  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :teachers do
    member do
      get :set_password
      patch :update_password
      post :set_availability
      get :availability
      get :child_enrollment
      match :bank_account, via: [:get, :post]
      get :get_price
      get :get_schedule
      post :tour_booking
      get :enroll_modal   
    end
    collection do
      get :document
      get :get_availability
      get :bank_account_detail
      get :manage_enrollment
    end
  end

  resources :children do
    member do
      get :abcd
    end
  end

  get '/parents/check_email_availability', to: 'parents#check_email_availability'
  get '/parents/dashboard', to: 'parents#dashboard'

  resources :parent_profiles

  resources :teacher_profiles do
    member do
      get :request_info
    end
  end

  resources :parents, only: [:create] do
    member do
      get :school
      get :interest_open_house
      match :payment, via: [:get, :post]
    end
    collection do
      get :change_favourite_status
      get :login
      get :child_birth
      get :set_child_admission
      put :toggle_favourite_status
    end
  end
  resources :enrollments do
    member do
      get :change_enrollment_status
    end
  end

  namespace :admin do
    get '', to: "teachers#index", as: :dashboard
    resources :teachers, only: [:index, :edit, :update] do
      member do
        match :price, via: [:get, :post]
        get :teacher_price
        get :edit_profile
        patch :approve
        patch :reject
        get :set_transaction
      end
      collection do
        match :upload_document, via: [:get, :post, :delete]
        get :document
        get :transaction_setting
      end
    end
    resources :parents
  end
  get '/partner', to: "teachers#new", as: :partner
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :check_if_teacher_or_admin, only: :index

    def index;    end

    def about_us;    end

    def terms_of_use;    end

    def privacy_policy;    end

    def faq_home_page;    end

    def search
      available_text = ['child care', 'child-care', 'daycare', 'provider', 'Toronto', 'Ontario', 'Calgary', 'Alberta']
      if params[:q].present? && available_text.exclude?(params[:q])
        @message = 'not found'
      else
        # if params[:q].present?
        #   @teachers = TeacherProfile.where("city ILIKE ?", "%#{params[:q]}%")
        #   if @teachers.blank?
        #     @teachers = TeacherProfile.near("%#{params[:q]}%", 50)
        #   end
        # else
          @teachers = TeacherProfile.all
        # end
        @hash = Gmaps4rails.build_markers(@teachers) do |teacher, marker|
          marker.lat teacher.latitude
          marker.lng teacher.longitude
          marker.picture({
            marker_anchor: [40, 58],
            url: ActionController::Base.helpers.asset_path("map_icon.png"),
            width: "45",
            height: "45"
          })
          marker.title teacher.school_name
          marker.infowindow render_to_string(:partial => "/welcome/info", locals: {:teacher => teacher})
        end
      end
    end

    def check_email
      @user = User.find_by(email: params[:email_id])
    end

    def show;    end

    def contact_us;    end

    def support
      UserMailer.support_mail(params[:name], params[:email], params[:subject], params[:message_body]).deliver_now
      redirect_back fallback_location: root_path
    end

  private
    def check_if_teacher_or_admin
        if current_user && (current_user.teacher? || current_user.admin?)
            redirect_to dashboard_path
        end
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def check_favourite id
    favourite = current_user.favourites.find_by(teacher_id: id)
    if favourite && favourite.status
      true
    else
      false
    end
  end
end

app/views/welcome/_footer.html.erb
<footer class="section_page_footer">
   <div class="custom_content_width_constraint">
      <div class="custom_grid Grid--full ">
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Child Care Near You</div>
               <a class="new-link link_blend" href="/l/ca/berkeley/child-care">Berkeley, CA</a><br><a class="new-link link_blend" href="/l/ca/los-angeles/child-care">Los Angeles, CA</a><br><a class="new-link link_blend" href="/l/ny/new-york/child-care">New York, NY</a><br><a class="new-link link_blend" href="/l/ca/oakland/child-care">Oakland, CA</a><br><a class="new-link link_blend" href="/l/ca/san-francisco/child-care">San Francisco, CA</a><br><a class="new-link link_blend" href="/l/ca/san-jose/child-care">San Jose, CA</a><br><a class="new-link link_blend" href="/l/ca/san-mateo/child-care">San Mateo, CA</a>
            </div>
         </div>
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Follow Us</div>
               <a class="new-link link_blend" href="https://blog.wonderschool.com" target="_blank">Blog</a><br><a class="new-link link_blend" href="https://www.facebook.com/joinwonderschool" target="_blank">Facebook</a><br><a class="new-link link_blend" href="https://instagram.com/wonderschools" target="_blank">Instagram</a><br><a class="new-link link_blend" href="https://twitter.com/wonderschools" target="_blank">Twitter</a>
            </div>
         </div>
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Wonderschool</div>
               <%=link_to 'About Us', about_path, class: 'new-link link_blend'%>
               <br>
               <%=link_to 'Terms of Use', terms_of_use_path, class: 'new-link link_blend'%>
               <br>
               <%=link_to 'Privacy Policy', privacy_policy_path, class: 'new-link link_blend'%>
            </div>
         </div>
         <div class="Grid-cell"><a class="new-link " href="/partner"><button class="button button_arrow  button_outline_blue" type="button">Partner with Wonderschool</button></a></div>
      </div>
   </div>
</footer>

app/views/welcome/_info.html.erb
<%= link_to teacher_profile_path(teacher) do %>
    <div class="row">
      <div class = "col-md-12">
        <div class = "thumbnail">
          <%= image_tag(teacher.profile_image.thumb, class: 'style_image')%>
        </div>
        <div class = "caption">
           <h3><%="#{teacher.first_name} #{teacher.last_name}"%></h3>
        </div>
      </div>
    </div>
<% end %>

app/views/welcome/_sign_in.html.erb
<div class="Section">
  <div class="P">
    <%= form_tag login_parents_path, id: 'sign_in_form', method: :get do |f| %>
      <div class="LoginForm-instructions">Please enter your password to log in.</div>
      <br>
      <div class="FormGroup">
        <div class="FormControl ">
          <label class="FormControl-label form_label_fields" for="ad959320-26e4-11e8-a2d4-d92d7563bdd4">Email</label><label class="FormControl-sublabel" for="ad959320-26e4-11e8-a2d4-d92d7563bdd4"></label>
          <div class="FormControl-control">
            <div class="TextInput   ">
              <%= text_field_tag :email, email, readonly: true, class: 'TextInput-control email_auth' %>
              <%#= f.input :email, label: false, input_html: {readonly: true, value: email }, class: 'TextInput-control' %>
              <!-- <input type="email" class="TextInput-control" id="ad959320-26e4-11e8-a2d4-d92d7563bdd4" placeholder="" value="anwar17ali@gmail.com" disabled="" spellcheck="false"> -->
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="FormGroup">
        <div class="FormControl ">
          <label class="FormControl-label form_label_fields" for="ad959321-26e4-11e8-a2d4-d92d7563bdd4">Password</label><label class="FormControl-sublabel" for="ad959321-26e4-11e8-a2d4-d92d7563bdd4"></label>
          <div class="FormControl-control">
            <div class="TextInput   ">
              <%= password_field_tag 'password', nil,  autocomplete: "off", class: "TextInput-control email_auth"%>
              <!-- <input type="password" class="TextInput-control" id="ad959321-26e4-11e8-a2d4-d92d7563bdd4" placeholder="" value="" spellcheck="true"> -->
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="LoginForm-emailFormForgotPassword">
        <!-- <a class="Link " href="#">Forgot Password?</a> -->
        <%= link_to "Forgot Password?", new_password_path('user') %>
      </div>
      <div class="FormActions "><button class="Button Button--full email_auth_submit" type="submit">Log In</button></div>
   <% end %>
  </div>
</div>

app/views/welcome/_sign_up.html.erb
<div id = 'sing_up_body'>
    <%= simple_form_for(Parent.new, url: parents_path, method: :post) do |f| %>
    <p>No account has been created with that email, but no worries, you can sign up now.</p>
    <div class="FormGroup">
      <div class="FormControl ">
        <label class="FormControl-label form_label_fields" for="2a62f520-268e-11e8-84d9-054058ff6835">Email</label><label class="FormControl-sublabel" for="2a62f520-268e-11e8-84d9-054058ff6835"></label>
        <div class="FormControl-control">
          <div class="TextInput">
            <%= f.input :email, label: false, input_html: {readonly: true, value: email,class:'email_auth' } %>
          </div>
        </div>
      </div>
    </div>
    <div class="FormGroup">
      <div class="FormControl">
        <label class="FormControl-label form_label_fields" for="2a631c30-268e-11e8-84d9-054058ff6835">First Name</label><label class="FormControl-sublabel" for="2a631c30-268e-11e8-84d9-054058ff6835"></label>
        <div class="FormControl-control">
          <div class="TextInput">
          <%= f.input :name, label: false,input_html:{class:'email_auth'} %>
          </div>
        </div>
      </div>
    </div>
    <div class="FormGroup">
      <div class="FormControl">
        <label class="FormControl-label form_label_fields" for="2a631c31-268e-11e8-84d9-054058ff6835">Last Name</label><label class="FormControl-sublabel" for="2a631c31-268e-11e8-84d9-054058ff6835"></label>
        <div class="FormControl-control">
          <div class="TextInput   ">
          <%= f.input :last_name, label: false,input_html:{class:'email_auth'} %>
          </div>
        </div>
      </div>
    </div>
    <div class="FormGroup">
      <div class="FormControl ">
        <label class="FormControl-label form_label_fields" for="2a631c32-268e-11e8-84d9-054058ff6835">Password</label><label class="FormControl-sublabel" for="2a631c32-268e-11e8-84d9-054058ff6835"></label>
        <div class="FormControl-control">
          <div class="TextInput   ">
          <%= f.input :password, label: false, autocomplete: "off",input_html:{class:'email_auth'} %>
          </div>
        </div>
      </div>
    </div>
    <div class="FormActions ">
      <div class="P">
      <button class="Button Button--full email_auth_submit" type="submit">Sign Up</button></div>
      <div class="P"><span class="ColoredText ColoredText--gray"><span class="SmallText">By performing this action, you agree to our <a class="Link " target="_blank" href="/terms_of_use">Terms&nbsp;of&nbsp;Use</a> and <a class="Link " target="_blank" href="/privacy_policy">Privacy&nbsp;Policy</a>.</span></span></div>
    </div>
  <% end %>
</div>

app/views/welcome/check_email.js.erb
<% if @user.present? %>
  $("#request_info_body").html('<%=j render("sign_in", email: params[:email_id])%>')
  $('#request_info_modal').modal('show')
<% else %>
  $("#request_info_body").html('<%=j render("sign_up", email: params[:email_id])%>')
  $('#request_info_modal').modal('show')
<% end %>

app/views/welcome/contact_us.html.erb
<header>
  <div class="header_section_center">
    <div class="content_center">
    	<div class="col-md-4 col-sm-4">
    		<%= link_to (image_tag('Dream_school_hd_logo.png', class: 'contact-logo')), root_path %>
    	</div>
    	<div class="col-md-8 col-sm-8 tablet_list">
	    	<ul class="inline_details_menus">
	    		<li>HOME</li>
	    		<li>ABOUT US</li>
	    		<li>DREAMCARE</li>
	    		<li>ENROLLMENT</li>
	    		<li class="active">CONTACT</li>
	    	</ul>
    	</div>
    </div>
  </div>
</header>
<div class="map_google">
	<div id="map" style="width:100%;height:400px;"></div>
<!--
To use this code on your website, get a free API key from Google.
Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
-->
</div>
<section class="contact_us col-md-12 col-sm-12 col-xs-12">
	<div class="center_area_content">
		<h2 class="conatct_heading">Contact Us</h2>
		<div class="col-md-6 col-sm-12 col-xs-12 no_padding_default">
			<p>The greatest happiness is family happiness. Give your family the joy of Dreamschool and our DreamCare App</p>
			<%= form_tag support_path,class:'contact_form_fields' do %>
				<div class="col-sm-12 col-xs-12 no_padding_default">
			  	<%= text_field_tag :name,nil,class:'name',placeholder:'Name *', required: true %>
			  </div>
				<div class="col-sm-12 col-xs-12 no_padding_default">
			  	<%= email_field_tag :email,nil,class:'Email',placeholder:'Email *', required: true %>
			  </div>
				<div class="col-sm-12 col-xs-12 no_padding_default">
			  	<%= text_field_tag :subject,nil,class:'Subject',placeholder:'Subject',required: true %>
			  </div>
			  <div class="col-sm-12 col-xs-12 no_padding_default">
			  	<%= text_area_tag :message_body,nil, class:'message',:size =>"9x6",placeholder:'Message', required: true %>
			  </div>
			  <%= submit_tag "Send",class:'submit_send_contact_info' %>
			<% end %>
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12 desktop_content">
			<p>For all inquiries, please complete the form to the left. More details will follow. Stay tuned!</p>
			<div class="style-imknta49" id="comp-imot2ny2"><div id="comp-imot2ny2line" class="style-imknta49line"></div></div>
			<address class="address_of_org">
				Centre for Social Innovation
				585 Dundas St. East, Torotno
			</address>
			<br>
		</div>
	</div>
</section>
<style type="text/css">
	.fixed-header {
		display: none;
	}
	#page-content {
		padding-top: 0px;
	}
</style>
<script type="text/javascript">
  $(function(){
    var mapOptions = {
      center: new google.maps.LatLng(43.653226, -79.3831843),
      zoom: 8
    };
		var handler = Gmaps.build('Google');
		handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
		    var markers = handlerhandler.addMarkers([
			    { lat: 43.653226, lng: -79.3831843}
			  ]);
		    handler.bounds.extendWith(markers);
		    handler.fitMapToBounds();
		});
})
</script>

app/views/welcome/faq_home_page.html.erb
<div class="wrap" role="document">
      <div class="content">
        <main class="main">
          
<section class="page-content editor-content no-carousel">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
         <div class="page-header">
        <p class="faq_heading_text">Frequently Asked Questions</p>
      </div>
<p><strong><a name="what"></a></strong></p>
<p><strong>1. What is Dreamschool?</strong><br>
Dreamschool is a network of quality, affordable in-home child care programs. We provide qualified child care providers with the support and tools they need to successfully start and run their own child care centres. At the same time, we connect parents with high-quality, affordable, reliable and convenient child care close to home.</p>

<p><strong>2. What is the Dreamschool model?</strong><br>
Dreamschool is designed with a child’s well-being in mind. We used the latest evidence in early childhood education and care and worked with experts in the field to design the Dreamschool model. To learn more, check out our <%=link_to 'About Us', about_path, class: 'faq_about_text'%> page. </p>

<p><strong>3. How can I sign up my child for Dreamschool?</strong><br> 
We are just months away from launching Dreamschool in your neighbourhood. To get on the waitlist, sign up <%= link_to 'here', new_user_registration_path, class: 'faq_sign_up_text' %>. We will be in touch very soon! </p>

<p><strong>4. What is the cost of enrolling my child in Dreamschool?</strong><br> Do you accept a subsidy?We are working to make sure that Dreamschool is the most affordable day care option for you. To get learn more, please reach out in our <%= link_to 'Contact Us', contact_path, class: 'faq_contact_text'%> page and we will be in touch shortly! </p>

<p><strong>5. Can the ratings of the provider be revealed before the visit?</strong><br>Unfortunately, the ratings cannot be provided until a visit to the provider occurs.</p>

<p><strong>6. How do you select your child care providers? What is the process?</strong><br>Your child’s well-being and safety is our #1 priority. This is why we have a thorough recruitment and vetting process to ensure that we answer all of your burning questions about your child’s day care provider.  Our process includes: </p>
<ul>
  <li>Police check </li>
  <li>First aid certification</li> 
  <li>Reference checks</li>  
  <li>Verification of educational and/or work experience</li> 
  <li>1:1 interview </li>
</ul>

<p>We also provide our care providers with training and 1:1 coaching support to set-up and maintain their daycare centre.</p> 
<p>Before your child is placed in a care provider’s home, we will share all the details and answer any questions you have.</p>
      </div>
    </div>
  </div>
</section>        </main><!-- /.main -->
      </div><!-- /.content -->
    </div>

app/views/welcome/search.html.erb
<div class="custom-search-section">
  <div class="row">
    <div class="col-md-8 col-sm-8 col-xs-12 custom-md">
      <div class="search_homepage_result">
        <div class="custom_content_width_constraint">
          <div class="custom_grid Grid--full ">
            <% if @message %>
              <div class="UnexpectedFailure-heading">Your search could not be found. Dreamschool only operates in Toronto at the moment.</div>
              <div class="UnexpectedFailure-heading">Don’t see a school in your neighborhood?
             <%= link_to 'Sign Up', new_user_registration_path %>
              Sign up to be notified when we open in your area.</div>
            <% else %>
              <% @teachers.each_with_index do |teacher, index|%>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <div class="Grid-cell   ">
                  	<%= link_to teacher_profile_path(teacher)  do %>
                    <!-- <a class="new-link" href="#"> -->
                      <div class="custom_callout_school">
                        <div class="custom_callout_school_aspect_ratio_image">
                          <%if teacher.profile_image.present?%>
                            <%= image_tag(teacher.profile_image.url, class: 'custom_callout_school_aspect_ratio_image_img')%>
                          <%end%>
                        </div>

                        <div class="custom_callout_school_info">
                          <h2 class="custom_callout_school_name"> <%= teacher.school_name %></h2>
                        </div>
                      </div>
                    <% end %>
                    <%= form_tag(change_favourite_status_parents_path, method: :get, remote: true)do %>
                      <%= hidden_field_tag 'teacher_id', teacher.teacher.id%>
                      <div class="custom_callout_school_bookmark enroll_btn" id = "teacher_image_<%=teacher.teacher.id%>">
                        <% if current_user && check_favourite(teacher.teacher.id) %>
                          <%= render 'parents/red_favourite' %>
                        <% else %>
                          <%= render 'parents/white_favourite' %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 custom-md">
    	<div class="fixed-map-4">
			  <div id="map" style='height: 100vh;'></div>
			</div>
    </div>
  </div>
</div>



<script type="text/javascript">

	$(function(){
    var mapOptions = {
      center: new google.maps.LatLng(43.653226, -79.3831843),
      zoom: 8
    };
		var handler = Gmaps.build('Google');
		handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
		    var markers = handler.addMarkers(<%=raw @hash.to_json %>);
		    handler.bounds.extendWith(markers);
		    handler.fitMapToBounds();
		});
})
</script>