config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about', to: 'welcome#about'
  get 'terms_of_use', to: 'welcome#terms_of_use'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'search', to: 'welcome#search'
  get 'show', to: 'welcome#show'
  get 'check_email', to: 'welcome#check_email'
  get :dashboard, to: 'teachers#dashboard', as: :dashboard
  get 'faq_home_page', to: 'welcome#faq_home_page'
  get '/contact_us', to: 'welcome#contact_us', as: :contact
  post 'support', to: 'welcome#support'



  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :teachers do
    member do
      get :set_password
      patch :update_password
      post :set_availability
      get :availability
      get :child_enrollment
      match :bank_account, via: [:get, :post]
      get :get_price
      get :get_schedule
      post :tour_booking
      get :enroll_modal   
    end
    collection do
      get :document
      get :get_availability
      get :bank_account_detail
      get :manage_enrollment
    end
  end

  resources :children do
    member do
      get :abcd
    end
  end

  get '/parents/check_email_availability', to: 'parents#check_email_availability'
  get '/parents/dashboard', to: 'parents#dashboard'

  resources :parent_profiles

  resources :teacher_profiles do
    member do
      get :request_info
    end
  end

  resources :parents, only: [:create] do
    member do
      get :school
      get :interest_open_house
      match :payment, via: [:get, :post]
    end
    collection do
      get :change_favourite_status
      get :login
      get :child_birth
      get :set_child_admission
      put :toggle_favourite_status
    end
  end
  resources :enrollments do
    member do
      get :change_enrollment_status
    end
  end

  namespace :admin do
    get '', to: "teachers#index", as: :dashboard
    resources :teachers, only: [:index, :edit, :update] do
      member do
        match :price, via: [:get, :post]
        get :teacher_price
        get :edit_profile
        patch :approve
        patch :reject
        get :set_transaction
      end
      collection do
        match :upload_document, via: [:get, :post, :delete]
        get :document
        get :transaction_setting
      end
    end
    resources :parents
  end
  get '/partner', to: "teachers#new", as: :partner
end

app/models/teacher.rb
class Teacher < User
  has_one :teacher_profile, foreign_key: :teacher_id, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  has_many :prices,  dependent: :destroy
  has_many :tour_requests, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :children
  has_many :payments
  has_many :enrollments
  delegate :first_name, :last_name, :street_address, :date_of_birth, to: :teacher_profile, allow_nil: true

  after_create :notify_admin_for_new_application
  # after_create :notify_support_and_user
  def notify_admin_for_new_application
    ['self.email', 'support@dreamschools.co', 'admin@dreamschool.com'].each do |email|
      UserMailer.notify_admin_for_new_application(self, email).deliver_now
    end
    #UserMailer.notify_admin_for_new_application(self).deliver_now
  end

  # def notify_support_and_user
  #   ['self.email', 'support@dreamschools.co'].each |email|
  #     UserMailer.notify_support_and_user(email).deliver_now
  #   end
  # end

end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::AdminBaseController
  before_action :set_teacher, except: [:index, :upload_document, :document, :transaction_setting]

  def index
    @teachers = Teacher.all.order(:id)
  end

  def edit_profile
    @teacher_profile = @teacher.teacher_profile.present? ? @teacher.teacher_profile : @teacher.build_teacher_profile
  end

  def update
    @teacher_profile = @teacher.teacher_profile.present? ? @teacher.teacher_profile : @teacher.build_teacher_profile
    if @teacher_profile.present? && @teacher_profile.update_attributes(permitted_teacher_params)
      flash[:notice] = 'Teacher profile successfully updated.'
      redirect_to admin_teachers_path
    else
      flash[:notice] = 'Something went wrong! Try again later.'
      render :new
    end
  end

  def approve
    if @teacher.present? && @teacher.update_attribute(:approve, true)
      UserMailer.teacher_invitaion_email(@teacher).deliver_now
      flash[:notice] = 'Teacher successfully approved.'
    else
      flash[:notice] = 'Something went wrong! Try again later.'
    end
    redirect_to admin_teachers_path
  end

  def reject
    if @teacher.present? && @teacher.update_attribute(:approve, false)
      flash[:notice] = 'Teacher successfully rejected.'
    else
      flash[:notice] = 'Something went wrong! Try again later.'
    end
    redirect_to admin_teachers_path
  end

  def price
    if request.get?
      @price = Price.new
      @teacher_prices = @teacher.prices if @teacher.prices.present?
    elsif request.post?
      @teacher.prices.destroy_all
      params[:price].each do |k, v|
        @price = @teacher.prices.new(child_time: v[:child_time].to_i, two_days_price: v[:two_days_price], three_days_price: v[:three_days_price], five_days_price: v[:five_days_price])
        if @price.save
          flash[:notice] = 'Teacher availability successfully created.'
        else
          flash[:notice] = 'Something went wrong! Try again later.'
        end
      end
      redirect_to teacher_price_admin_teacher_path(@teacher)
    end
  end

  def teacher_price
    @prices = @teacher.prices
  end

  def upload_document
    if request.get?
      @document = AdminInfo.new
    elsif request.post?
      @document = AdminInfo.new(document_params)
      if @document.save
        redirect_to document_admin_teachers_path, notice: "The document #{@document.name} has been uploaded."
      else
        render "upload_documnet"
       end
    elsif request.delete?
      @document = AdminInfo.find(params[:document_id])
      if @document.destroy
        redirect_to document_admin_teachers_path, notice: "The document #{@document.name} has been deleted."
      else
        redirect_to document_admin_teachers_path, notice: "Something went wrong! Try again later."
       end
    end
  end

  def document 
    @documents = AdminInfo.all
  end

  def transaction_setting
    @teacher = Teacher.all
  end

  def set_transaction
    teacher_profile = TeacherProfile.find(params[:id])
    teacher_profile.update_attributes(transaction_fee: params[:teacher_profile][:transaction_fee])
    redirect_to transaction_setting_admin_teachers_path, notice: 'transaction_fee successfully created'
  end

  private
    def permitted_teacher_params
      params.require(:teacher_profile).permit(
        :first_name, :last_name, :street_address,
        :apt_no, :city, :home_phone, :cell_phone,
        :date_of_birth, :language, :work,
        :legal_to_work, :apartment, :floor,
        :condo, :house, :basement_premises, :two_exit,
        :home_smoke, :pet, :vaccine, :goal, :age_range,
        :local_school, :school_name, :request_info, :tour, :open_house,
        :comments, :profile_image, :cover_photo,
        children_attributes: [:id, :full_name, :age, :care_by, :_destroy]
      )
    end

    def permmited_price_param
      params.require(:price).permit(
        :child_time, :two_days_price, :three_days_price, :five_days_price
      )
    end

    def document_params
      params.require(:admin_info).permit(
        :name, :document
        )
    end

    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  layout :set_layout
  before_action :authenticate_user!, except: [:show, :new, :create, :set_password, :update_password]
  before_action :authenticate_user!, except: [:show, :new, :create, :set_password, :update_password]
  before_action :set_teacher, only: [ :update_password, :set_password ]
  before_action :ensure_teacher, only: [:dashboard, :child_enrollment]

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(permitted_teacher_params)
    if @teacher.save
      @teacher.invitation_token
      redirect_to root_path, notice: "Thanks for register, We are reviewing your application. You will receive an email upon approval of your profile."
    else
      redirect_to partner_path, alert: "Something went wrong! Please try again."
    end
  end

  def show
  end

  def update_password
    if @teacher.update(permitted_teacher_password_params)
      bypass_sign_in(@teacher)
      redirect_to new_teacher_profile_path, notice: 'Your password has been set successfully. You can now update your profile.'
    else
      redirect_to root_path, alert: 'Password could not be set.'
    end
  end

  def dashboard
    unless current_user.teacher_profile.presence
      redirect_to new_teacher_profile_path, notice: 'You need to update your profile!'
    end
  end

  def enroll_modal;  end

  def document
    @documents = AdminInfo.all
  end

  def get_price
    teacher = Teacher.find(params[:id])
    redirect_to teacher_profile_path(teacher.teacher_profile) unless request.xhr?
    @prices = Teacher.find(params[:id]).prices
  end

  def get_schedule
    @tour_request = TourRequest.new
    @teacher = Teacher.find(params[:id])
    day = params[:date].to_date.wday == 0 ? 7 : params[:date].to_date.wday
    availabilty = @teacher.availabilities.where(day_index: day)
    if availabilty.present?
      @start_time = availabilty.first.start_time.to_s(:time)
      @end_time = availabilty.first.end_time.to_s(:time)
    end
  end

  def tour_booking
    @teacher = Teacher.find(params[:id])
    tour_request = current_user.tour_requests.new(permitted_tour_request_param)
    @status = tour_request.save ? true : false
  end

  def availability
  end

  def set_availability
    calander_events = JSON.parse(params[:calander_events])
    if calander_events.present?
      current_user.availabilities.destroy_all
      calander_events.each do |ce|
        @availability = current_user.availabilities.new(day_index: ce["week_day"], start_time: ce["hour_from"], end_time: ce["hour_to"])
        if @availability.save
          flash[:notice] = 'Teacher availability successfully created.'
        else
          flash[:notice] = 'Something went wrong! Try again later.'
        end
      end
    end
    redirect_to availability_teacher_path
  end

  def get_availability
    get_availabilities = current_user.availabilities
    availabilities = get_availabilities.map do |availabilitly|
      {
        day_of_week: availabilitly.day_index,
        start_hour: availabilitly.start_time.strftime("%H:%M:%S"),
        end_hour: availabilitly.end_time.strftime("%H:%M:%S")
      }
    end
    render json: availabilities
  end

  def bank_account_detail
    stripe_account_id = current_user.teacher_profile.stripe_account_id
    begin
      @stripe_account_details = Stripe::Account.retrieve(stripe_account_id)
    rescue Exception => e
      redirect_to dashboard_path, alert: e.message
    end
  end

  def bank_account
    unless request.get?
      file = File.new(params[:stripe_verification_file].path) rescue nil
      upload_result = upload_identity(file)
      begin
        stripe_account = Stripe::Account.create({
          type: 'custom',
          country: 'US',
          email: current_user.email,
          legal_entity: {
            type: 'individual',
            first_name: current_user.first_name,
            last_name:  current_user.last_name,
            address: {
              city: params[:address_city],
              state: params[:address_state],
              country: 'US',
              postal_code: params[:address_postal_code],
              line1: params[:address_line1],
            },
            dob: {
              day: params[:birth_date].to_date.day,
              month: params[:birth_date].to_date.month,
              year: params[:birth_date].to_date.year,
            },
            verification: {
              document: upload_result.id,
            },
          },
          external_account: {
            object: 'bank_account',
            country: 'US',
            currency: 'usd',
            account_number: params[:bank_account_number],
            account_holder_name: params[:bank_holder_name],
            routing_number: params[:bank_routing_number],
            account_holder_type: 'individual',
          },

          tos_acceptance: {
            date: Time.now.to_i,
            ip: request.remote_ip,
          }
        })

        current_user.teacher_profile.update_attributes(stripe_account_id: stripe_account.id) if stripe_account.present?
        redirect_to bank_account_detail_teachers_path, notice: 'Your Bank account information is successfully updated'
      rescue Stripe::StripeError => e
        flash[:error] = e.message
        render 'bank_account'
      end
    end
  end

  def manage_enrollment
    @enrollments = current_user.enrollments
  end

  def set_password
    @teacher
  end

  def child_enrollment
    enroll = Enrollment.find(params[:enroll])
    if params[:status]
      enroll.update_attributes(status: params[:status])
      UserMailer.make_payment_link(enroll).deliver_now
    else
      enroll.update_attributes(status: params[:status])
    end
    redirect_to dashboard_path
  end
end
  private

    def upload_identity(file)
      Stripe::FileUpload.create(
        {
          purpose: 'identity_document',
          file: file
        },
      )
    end

    def set_teacher
      @teacher ||= Teacher.find_by(invitation_token: params[:token])
    end

    def permitted_teacher_password_params
      params.require(:teacher).permit(
        :password,
        :password_confirmation
      )
    end

    def permitted_tour_request_param
      params.require(:tour_request).permit(
        :tour_date,
        :tour_time,
        :phone,
        :teacher_id
      )
    end

    def permitted_teacher_params
      params[:teacher][:password] = Devise.friendly_token.first(8)
      params.require(:teacher).permit(
        :name,
        :email,
        :telephone_no,
        :postal_code,
        :password
      )
    end

    def set_layout
      case action_name
      when 'dashboard', 'availability', 'bank_account', 'bank_account_detail', 'document', 'manage_enrollment'
        'admin'
      else
        'application'
      end
    end

    def ensure_teacher
      unless current_user && current_user.teacher?
        redirect_to admin_dashboard_path
      end
    end

app/helpers/admin/teachers_helper.rb
module Admin::TeachersHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_booked_message.html.erb
<div id = "show_message">
  <div class="AlignedText AlignedText--center">
    <% unless status %>
      <div class="Section">
        <div class="P">
          <div class="H3">Something went wrong! Try again later.</div>
        </div>
    <% else %>
      <div class="Section">
        <div class="P">
          <div class="H3">We’ve received your tour request.</div>
        </div>
        <div class="P">We will be in touch soon to confirm your requested time or suggest an alternate time.</div>
      </div>
      <div class="Section">
        <div class="P">
          <div class="H5 ">Would you like to see other great programs in your area?</div>
        </div>
      <% end %>
      <div class="P">
        <%= link_to 'Show me more programs', teacher_profile_path(teacher_profile), class: "Button email_auth_submit"%>
      </div>
    </div>
  </div>
</div>

app/views/teachers/_enroll_modal.html.erb
<div id="apply_enroll_modal" class="modal fade" role="dialog">
  <div class="modal-dialog enroll_modal_dilog">
    <div class="modal-content">
      <div class="Modal-contentWrapper">
        <button type="button" class="close position_top_corner" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <div class="Modal-header ">
          <div class="Modal-title">Apply to Enroll</div>
        </div>
        <div class="Modal-body " id="enroll_modal_append">
          
        </div>
      </div>
     </div>
  </div>
</div>

app/views/teachers/_set_price.html.erb
<div class="SchoolPagePricingModal-pricing">
  <% @prices.each do |price|%>
    <table class="SchoolPage-table">
      <tbody>
        <tr>
          <td colspan="2" class="SchoolPage-tableHeader">
          <%= price.child_time%></td>
        </tr>
        <tr class="SchoolPage-tableRow ">
          <td class="SchoolPage-tableKey">2 days/wk</td>
          <td class="SchoolPage-tableValue">$<%= price.two_days_price%></td>
        </tr>
        <tr class="SchoolPage-tableRow ">
          <td class="SchoolPage-tableKey">3 days/wk</td>
          <td class="SchoolPage-tableValue">$<%= price.three_days_price%></td>
        </tr>
        <tr class="SchoolPage-tableRow ">
          <td class="SchoolPage-tableKey">5 days/wk</td>
          <td class="SchoolPage-tableValue">$<%= price.five_days_price%></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/teachers/availability.html.erb
<div id="timeslot-cal-container">
  <%= form_tag set_availability_teacher_path, id: 'availability_form', method: :post do |f| %>
    <%= hidden_field_tag "person_id", current_user.id, id: "person_id" %>
    <%= link_to "Reset", "javascript:void(0);", id: "clear", class: "btn btn-primary" %>
    <div id="timeslot-cal"></div>
    <%= submit_tag 'Save availability',  data: {disable_with: "Wait..." }, class: "send_button_account button" %>
  <% end %>
</div>

app/views/teachers/bank_account.html.erb
<div class="form-content custom-form-content">
  <%= form_tag bank_account_teacher_path, id: 'stripe_form',  method: :post, class: 'form-horizontal', multipart: true do |f| %>

    <!-- <div class='form-group'>
      <%#= label_tag :first_name, 'First Name *' %>
      <%#= text_field(:account_info, :first_name, required: true ) %>
      <%#= text_field_tag :first_name, nil, required: true, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%#= label_tag :last_name, 'Last Name *' %>
      <%#= text_field(:account_info, :last_name, required: true ) %>
      <%#= text_field_tag :last_name, nil, required: true, class: 'form-control' %>
    </div> -->

    <!-- <div class='form-group'>
      <%#= label_tag :email, 'Email *' %>
      <%#= email_field(:account_info, :email, required: true ) %>
      <%#= email_field_tag :email, nil, required: true, class: 'form-control' %>
    </div> -->

    <div class='form-group'>
      <%= label_tag :address, 'Address *' %>
      <%= text_field_tag :address_line1, nil, required: true, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= label_tag :city, 'City *' %>
      <%= text_field_tag :address_city, nil, required: true, class: 'form-control' %>
    </div>


    <div class='form-group'>
      <%= label_tag :state, 'State *' %>
      <%= text_field_tag :address_state, nil, required: true, class: 'form-control'  %>
    </div>

    <div class='form-group'>
      <%= label_tag :postal_code, 'Postal Code *' %>
      <%= text_field_tag(:address_postal_code, nil, required: true, class: 'form-control') %>
    </div>

    <div class='form-group'>
      <%= label_tag :date_of_birth, 'Date of birth *' %>
      <%= text_field_tag :birth_date, nil, required: true, readonly: true, placeholder: 'dd/mm/yyyy', class: 'form-control dob custom-dob' %>
    </div>

    <div class='form-group'>
      <%= label_tag :account_number, 'Account holder name *' %>
      <%= text_field_tag(:bank_holder_name, nil, required: true, class: 'form-control') %>
    </div>
    <div class='form-group'>
      <%= label_tag :account_number, 'Account Number *' %>
      <%= text_field_tag(:bank_account_number, nil, required: true, class: 'form-control') %>
    </div>

    <div class='form-group'>
      <%= label_tag :routing_number, 'Rounting Number *' %>
      <%= text_field_tag(:bank_routing_number, nil, required: true, class: 'form-control') %>
    </div>

    <div class='form-group'>
      <%= label_tag :verification_file, 'Verification Document *' %>
      <%= file_field_tag 'stripe_verification_file', required: true, accept: 'image/png,image/gif,image/jpeg' %>
    </div>

    <%= submit_tag "Submit", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/teachers/document.html.erb
<div class="form-content">
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |doc| %>
      <tr>
        <td><%= doc.name %></td>
        <td><%= link_to "Download Document", doc.document_url, download: doc.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/teachers/manage_enrollment.html.erb
<h1>Teachers applications</h1>
<table class="table">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Date of Birth</th>
      <th>Place of Birth</th>
      <th>Gender</th>

      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |e| %>    
      <tr>
        <td><%= e.child.full_name %></td>
        <td><%= e.child.date_of_birth %></td>
        <td><%= e.child.place_of_birth %></td>
        <td><%= e.child.gender %></td>
        <td>
          <% if e.status %>
          <%= link_to 'Accept', change_enrollment_status_enrollment_path(e), class:'btn btn-sm btn-primary'%> 
          <% else %>
           <%= link_to 'Reject', change_enrollment_status_enrollment_path(e), class:'btn btn-sm btn-danger'%> 
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/new.html.erb
<div>
  <div class="new_image_hero">
    <div class="new_image_hero_image"></div>
    <div class="new_image_hero_content">
      <div class="custom_content_width_constraint">
        <div class="new_partner_page_hero">
          <div class="new_partner_page_hero_messaging">
            <h1 class="new_partner_page_hero_messaging_head">Dreaming about opening your own preschool or child care&nbsp;program?</h1>
            <h2 class="new_partner_page_hero_messaging_subhead">We want to hear all about&nbsp;it.</h2>
          </div>
          <div class="new_partner_page_hero_cta">
            <div class="new_partner_page_hero_cta_form">
              <h3 class="new_partner_page_hero_cta_head">Schedule a free 15 minute chat with our team to discuss your vision!</h3>
              <div class="new_prospect_capture_form">
                <%= simple_form_for(@teacher) do |f| %>
                  <div class="new_prospect_capture_form_form_control">
                    <div class="new_text_input">
                      <%= f.text_field :name, :placeholder => "Name", class: 'form-control new_text_input_control', required: true %>
                    </div>
                  </div>
                  <div class="new_prospect_capture_form_form_control">
                    <div class="new_text_input">
                      <%= f.email_field :email, :placeholder => "Email", class: 'form-control new_text_input_control', required: true %>
                    </div>
                  </div>
                  <div class="new_prospect_capture_form_form_control">
                    <div class="new_text_input">
                      <%= f.text_field :telephone_no, :placeholder => "Telephone Number", class: 'form-control new_text_input_control', required: true %>
                    </div>
                  </div>
                  <div class="new_prospect_capture_form_form_control">
                    <div class="new_text_input">
                      <%= f.text_field :postal_code, :placeholder => "Postal Code", class: 'form-control new_text_input_control', required: true %>
                    </div>
                  </div>
                  <div class="new_prospect_capture_form_form_control">
                    <div class="P">
                      <%= f.submit 'Submit', class: "button button_full button__large button_arrow" %>
                    </div>
                  </div>
                  <div class="P">
                    <span class="new_colored_text new_colored_text__gray">
                      <span class="small_text">By performing this action, you agree to our&nbsp;
                      <%= link_to ' Terms  of  use', terms_of_use_path, class: 'new-link', target: 'blank'%> &nbsp;and&nbsp;
                     <%= link_to 'Privacy Policy', privacy_policy_path, class: 'new-link', target: 'blank'%>
                      </span>
                    </span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="new_partner_page_section new_partner_page_section__white">
    <div class="custom_content_width_constraint">
      <h3 class="new_partner_page_section_head">Why start your own Dreamschool? </h3>
      <div class="new_partner_page_why_grid">
        <div class="new_partner_page_why_grid_cell">
          <div class="new_partner_page_why_grid_content">
            <div class="new_partner_page_section_subhead">1. Focus your time on what you love most</div>
            It can be daunting and scary to start your own business. So we take care of all the business stuff, so you can focus on what you love most – delivering child care!
          </div>
        </div>
        <div class="new_partner_page_why_grid_cell">
          <div class="new_partner_page_why_grid_content">
            <div class="new_partner_page_section_subhead">2. You join the Dreamschool network </div>
            Get all the support you need to start and manage your own child care centre –stress-free! Use our program model and use our online platform that helps fill spots quickly.
          </div>
        </div>
        <div class="new_partner_page_why_grid_cell">
          <div class="new_partner_page_why_grid_content">
            <div class="new_partner_page_section_subhead">3. Make more money</div>
            You can earn more money than in traditional childcare centres – up to 50% more than the average child care centre in Toronto.
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="new_partner_page_section">
    <div class="custom_content_width_constraint">
      <h3 class="new_partner_page_section_head">Why partner with Dreamschool?</h3>
      <div class="new_partner_page_section_narrow">
        <div class="new_partner_page_how_grid">
          <div class="new_partner_page_how_grid_content">
            <ol class="new_partner_page_how_grid_list">
              <li> 1-on-1 launch and licensing support</li>
              <li> Effective approach and platform to fill and manage your care centre</li>
              <li> Easy-to-use online bill and management tools</li>
              <li> Connect to the Dreamschool Network</li>
            </ol>
          <div class="new-patner-para">
           <p> For more information, see “how it works”.</p>
          </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="new_partner_page_section new_partner_page_section__blue">
    <div class="custom_content_width_constraint">
      <h3 class="new_partner_page_section_head">Get in touch to explore your dreams!  </h3>
      <div class="new_aligned_text new_aligned_text__center">
        <div class="new_partner_page_section_narrow">
          <div class="new_partner_page_bottom_cta_form">
            <div class="new_prospect_capture_form">
              <%= simple_form_for(@teacher) do |f| %>
                <div class="new_prospect_capture_form_form_control">
                  <div class="new_text_input new_text_input__white">
                    <%= f.text_field :name, :placeholder => "Name", class: 'form-control new_text_input_control', required: true %>
                  </div>
                </div>
                <div class="new_prospect_capture_form_form_control">
                  <div class="new_text_input new_text_input__white">
                    <%= f.email_field :email, :placeholder => "Email", class: 'form-control new_text_input_control', required: true %>
                  </div>
                </div>
                <div class="new_prospect_capture_form_form_control">
                  <div class="new_text_input new_text_input__white">
                    <%= f.text_field :telephone_no, :placeholder => "Telephone Number", class: 'form-control new_text_input_control', required: true %>
                  </div>
                </div>
                <div class="new_prospect_capture_form_form_control">
                  <div class="new_text_input new_text_input__white">
                    <%= f.text_field :postal_code, :placeholder => "Postal Code", class: 'form-control new_text_input_control', required: true %>
                  </div>
                </div>
                <div class="new_prospect_capture_form_form_control">
                  <div class="P">
                    <%= f.submit 'Submit', class: "button button_full button__large button_arrow  button__white" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="new_partner_page_section_narrow"><br>
          <p>Do you enjoy working with children? Do you want to work for yourself and own your own child care centre? Do you live in Toronto or its surrounding area? Let’s talk about it!</p>
          <p>Schedule an appointment to meet our team today!</p>
          <div class="P">
            <div class="Ttos_agree_light">
              <span class="colored_text colored_text_white">
              <span class="small_text">By performing this action, you agree to your  and <%= link_to ' Terms  of  use', terms_of_use_path, class: 'text_underline', target: 'blank'%> and
              <%= link_to 'Privacy Policy', privacy_policy_path, class: 'text_underline', target: 'blank'%>.
                </span>
              </span>
            </div>                    
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>


  <!-- <div class="new_partner_page_section new_partner_page_section__blue">
    <div class="custom_content_width_constraint">
      <h3 class="new_partner_page_section_head">Get in touch to explore your dreams! </h3>
      <div class="new_aligned_text new_aligned_text__center">
        <div class="new_partner_page_section_narrow">
          <p>Do you enjoy working with children? Do you want to work for yourself and own your own child care centre? Do you live in Toronto or its surrounding area? Let’s talk about it!</p>
          <p>Schedule an appointment to meet our team today!</p>
          <p>By performing this action, you agree to your Terms of Use and Privacy Policy. </p>
        </div>
      </div>
    </div>
  </div> -->
</div>

app/views/teachers/set_password.html.erb
<div class="login-signup-form">
  <div class="form-content custom-form-content">
    <h1> Set password </h1>
    <%= simple_form_for(@teacher, url: update_password_teacher_path(token: params[:token]), method: :patch, html: {class: 'form-horizontal'}) do |f| %>
      <%= f.hidden_field :invitation_token %>
      <%= f.input :email, input_html: {readonly: true} %>  
      <em>(8 characters minimum)</em><br />
      <%= f.input :password, label: "Password", autofocus: true, autocomplete: "off" %>
      <%= f.input :password_confirmation, label: "Confirm password", autofocus: true, autocomplete: "off" %>

      <div class="form-actions">
        <%= f.submit "Set Password", class: 'btn btn-custom' %>
      </div>

    <% end %>
  </div>
</div>

app/views/teachers/show.html.erb
WELCOME