config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about', to: 'welcome#about'
  get 'terms_of_use', to: 'welcome#terms_of_use'
  get 'privacy_policy', to: 'welcome#privacy_policy'
  get 'search', to: 'welcome#search'
  get 'show', to: 'welcome#show'
  get 'check_email', to: 'welcome#check_email'
  get :dashboard, to: 'teachers#dashboard', as: :dashboard
  get 'faq_home_page', to: 'welcome#faq_home_page'
  get '/contact_us', to: 'welcome#contact_us', as: :contact
  post 'support', to: 'welcome#support'



  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :teachers do
    member do
      get :set_password
      patch :update_password
      post :set_availability
      get :availability
      get :child_enrollment
      match :bank_account, via: [:get, :post]
      get :get_price
      get :get_schedule
      post :tour_booking
      get :enroll_modal   
    end
    collection do
      get :document
      get :get_availability
      get :bank_account_detail
      get :manage_enrollment
    end
  end

  resources :children do
    member do
      get :abcd
    end
  end

  get '/parents/check_email_availability', to: 'parents#check_email_availability'
  get '/parents/dashboard', to: 'parents#dashboard'

  resources :parent_profiles

  resources :teacher_profiles do
    member do
      get :request_info
    end
  end

  resources :parents, only: [:create] do
    member do
      get :school
      get :interest_open_house
      match :payment, via: [:get, :post]
    end
    collection do
      get :change_favourite_status
      get :login
      get :child_birth
      get :set_child_admission
      put :toggle_favourite_status
    end
  end
  resources :enrollments do
    member do
      get :change_enrollment_status
    end
  end

  namespace :admin do
    get '', to: "teachers#index", as: :dashboard
    resources :teachers, only: [:index, :edit, :update] do
      member do
        match :price, via: [:get, :post]
        get :teacher_price
        get :edit_profile
        patch :approve
        patch :reject
        get :set_transaction
      end
      collection do
        match :upload_document, via: [:get, :post, :delete]
        get :document
        get :transaction_setting
      end
    end
    resources :parents
  end
  get '/partner', to: "teachers#new", as: :partner
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<div class="automatic_fadeout">
	  <div class="<%= flash_class(key) %>">
	    <%= value %>
	  </div>
  </div>
<% end %>
<script type="text/javascript">
  // setTimeout(function() {
  //   $('.automatic_fadeout').fadeOut();
  // }, 4000);
</script>

app/views/layouts/_footer.html.erb
<footer class="col-md-12 col-sm-12 col-xs-12 section_page_footer">
   <div class="custom_content_width_constraint">
      <div class="custom_grid Grid--full ">
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Child Care Near You</div>
               <a class="new-link link_blend" href="#">Toronto, Ontario</a>
               <br>
               <a class="new-link link_blend" href="#">Calgary, Alberta</a>
               <!-- <br>
               <a class="new-link link_blend" href="#">Calgary</a>
               <br>
               <a class="new-link link_blend" href="#">Albert</a> -->
            </div>
         </div>
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Follow Us</div>
               <a class="new-link link_blend" href="#" target="_blank">Blog</a>
               <br>
               <a class="new-link link_blend" href="#" target="_blank">Facebook</a>
            </div>
         </div>
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Contact</div>
                <%= link_to 'Contact Us', contact_path, class: 'new-link link_blend'%>
               <br>
               <span>Address:
                <p>
                  Centre for Social Innovation<br>
                  585 Dundas St. East, Toronto
                </p>
               </span>
            </div>
         </div>
         <div class="Grid-cell">
            <div>
               <div class="section_page_footer_link_list_title">Dreamcare</div>
               <%=link_to 'About Us', about_path, class: 'new-link link_blend'%>
               <br>
               <%=link_to 'Jobs', 'javascript:void(0)', class: 'new-link link_blend'%>
               <br>
               <%=link_to 'FAQ', faq_home_page_path, class: 'new-link link_blend'%>
               <br>
               <%=link_to 'Terms of Use', terms_of_use_path, class: 'new-link link_blend'%>
               <br>
               <%=link_to 'Privacy Policy', privacy_policy_path, class: 'new-link link_blend'%>
            </div>
         </div>
         <div class="Grid-cell"><a class="new-link " href="<%=partner_path%>"><button class="button button_arrow  button_outline_blue" type="button">Partner with Dreamschools</button></a></div>
      </div>
   </div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-header">
  <nav class="navbar navbar-default custom-navbar" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to (image_tag('dreamschool.png', class: 'school-logo')), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <div class="">
        <%= form_tag search_path, id: 'search_form', method: :get do |f| %>
          <!-- <form class="" role="search"> -->
            <div class="input-group page_header_desktop_search_control">
            <%= text_field_tag :q, nil, placeholder: "Where are you looking for child care?", class: 'form-control page_header_desktop_search_input' %>
            <!-- <input type="text" class="form-control page_header_desktop_search_input" placeholder="Where are you looking for child care?" name="q"> -->
            <div class="input-group-btn">
              <button class="btn btn-default custom_page_header_desktop_search_submit_button" type="submit"><i class="glyphicon glyphicon-search submit-search-icon"></i></button>
            </div>
            </div>
        <% end %>
        <!-- </form> -->
      </div>
      <ul class="nav navbar-nav navbar-right custom-right-navbar">
        <li><span class="glyphicon glyphicon-th-list my-toggle"></span></li>
        <%if current_user %>
          <% if current_user.parent? %>
            <li><%= link_to 'MY SCHOOLS',  school_parent_path(current_user), class:'nav-link' %>
            <!-- <a href="/partner" class="nav-link">MY SCHOOLS</a></li> -->
            <% if current_user.parent_profile.present? %>
              <li><%= link_to 'FAMILY PROFILE',  parent_profile_path(current_user.parent_profile&.id), class:'nav-link' %></li>
            <% else %>
              <li><%= link_to 'FAMILY PROFILE',  new_parent_profile_path, class:'nav-link' %></li>
            <% end %>
          <% else %>
            <li><%=link_to 'ABOUT', about_path, class: 'nav-link'%></li>
            <li><a href="<%=dashboard_path%>" class="nav-link">DASHBOARD</a></li>
          <% end %>
          <li><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %></li>
        <%else%>
          <li><%=link_to 'ABOUT', about_path, class: 'nav-link'%></li>
          <li><a href="/partner" class="nav-link">START A DREAMSCHOOL</a></li>
          <li><%= link_to 'LOG IN', new_user_session_path %></li>
          <li><%= link_to 'SIGN UP', new_user_registration_path %></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
  <div class="desktop-menu">
    <ul class="desktop-menu-list">
      <li><%=link_to 'ABOUT', about_path, class: 'nav-link'%></li>
      <li><a href="/partner" class="nav-link">START A DREAMSCHOOL</a></li>
    </ul>
  </div>

</header>


<script>
  $(document).ready(function(){
      $(".my-toggle").click(function(){
        $(".desktop-menu").toggle();
      });
  });
</script>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">Dashboard</a>
    </li>
    <%if current_user.admin? %>
      <li class="<%=is_active_menu('index')%>">
        <%= link_to 'Teachers', admin_teachers_path %>
      </li>
      <li class="<%=is_active_menu('document')%> <%=is_active_menu('upload_document')%>">
        <%= link_to 'Curriculum PDF', document_admin_teachers_path %>
      </li>
      <li class="<%=is_active_menu('bank_account')%>" >
        <%= link_to 'Transaction Fee Setting',  transaction_setting_admin_teachers_path %>
      </li>
      <!-- <li>
        <%= link_to 'Parents Applications', admin_parents_path %>
      </li> -->
    <%elsif current_user.teacher? %>
      <li  class=" <%=is_active_menu('edit')%>">
        <%settings_path = current_user.teacher_profile ? edit_teacher_profile_path(current_user.teacher_profile) : new_teacher_profile_path%>
        <%= link_to 'Profile Details', settings_path %>
      </li>
      <li class="<%=is_active_menu('document')%>">
        <%= link_to 'Curriculum PDF', document_teachers_path %>
      </li>
      <li class="<%=is_active_menu('bank_account')%>" >
        <%= link_to 'Bank Account Settings', bank_account_teacher_path(current_user) %>
      </li>
      <li class="<%=is_active_menu('availability')%>" >
        <%= link_to 'Scheduling Availability', availability_teacher_path(current_user) %>
      </li>
      <li class="<%=is_active_menu(' Managing Enrollment pages')%>">
        <%= link_to 'Managing Enrollment page', manage_enrollment_teachers_path %>
      </li>
      <li>
        <%= link_to 'Parents Applications', admin_parents_path %>
      </li>
      <!-- <li>
        <a href="#">Payments</a>
      </li> -->
    <%end%>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDs</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js" %>
    <%#= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.8.0/fullcalendar.min.js"%>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/flash_messages'%>
    <div id="page-content" class="<%=flash.present? ? 'flash-page-content' : ''%>">
      <div id="wrapper" class="toggled custom-admin-wrapper">
        <%= render partial: 'layouts/sidebar'%>
        <div id="page-content-wrapper">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDs</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700|Merriweather" rel="stylesheet">
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyDVNuWNguQz4vB25OdDpztwxE3QR_CzG0g" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"%>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"%>
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/flash_messages'%>
    <div id="page-content" class="<%=flash.present? ? 'flash-page-content' : ''%>">
      <%= yield %>
      <% unless action_name == 'search' %>
        <%= render 'layouts/footer'%>
      <% end %>
    </div>
  </body>
</html>